spring:
  application:
    name: springai3

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma:2b
          temperature: 0.7
      init:
        pull-model-strategy: when_missing
        timeout: 60s
        max-retries: 1


