spring:
  application:
    name: springai5

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: huihui_ai/kanana-nano-abliterated


  config:
    import: application-secret.yml


