spring:
  application:
    name: springai4

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: hf.co/bartowski/gemma-2-2b-it-GGUF
          temperature: 0.7
      init:
        pull-model-strategy: when_missing
        timeout: 60s
        max-retries: 1




